"""FEN encode/decode tests (core/fen.py).

Built for V0.6.2 (talking to an external Pikafish process) -- see
`docs/v0.6.2.md`. Pays particular attention to the piece-letter
convention (Horse=N, Elephant=B, NOT this project's own internal
`PieceType.value` strings) since that's the single easiest thing to
get subtly wrong here (see fen.py's own module docstring).
"""

import pytest

from alphazetacchess.core.board import Board
from alphazetacchess.core.piece import Color, Piece, PieceType
from alphazetacchess.core.zobrist import Zobrist
from alphazetacchess.core.fen import board_to_fen, board_from_fen


def empty_board():
    board = Board()
    board.board = [[None for _ in range(Board.WIDTH)] for _ in range(Board.HEIGHT)]
    board.history = []
    board.current_player = Color.RED
    board.zobrist_hash = Zobrist.board_hash(board)
    return board


def put(board, piece_type, color, x, y):
    board.board[y][x] = Piece(piece_type, color, x, y)


# ---------------------------------------------------------------------------
# board_to_fen
# ---------------------------------------------------------------------------

def test_starting_position_matches_the_well_known_standard_fen():
    board = Board()

    fen = board_to_fen(board)

    assert fen == "rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1"


def test_uses_ucci_letters_not_this_projects_own_piecetype_value():
    # PieceType.HORSE.value is "H" and PieceType.ELEPHANT.value is "E"
    # internally -- but Pikafish/UCCI FEN uses N (knight) and B
    # (bishop) respectively. If this test ever starts failing because
    # someone "simplified" fen.py to use piece.type.value directly,
    # that's the bug this test exists to catch.
    board = empty_board()
    put(board, PieceType.HORSE, Color.RED, 0, 0)
    put(board, PieceType.ELEPHANT, Color.BLACK, 8, 9)

    fen = board_to_fen(board)
    placement = fen.split()[0]

    assert "H" not in placement and "h" not in placement
    assert "E" not in placement and "e" not in placement
    assert placement.split("/")[0] == "8b"  # Black elephant, rank 9
    assert placement.split("/")[-1] == "N8"  # Red horse, rank 0


def test_active_color_maps_red_to_w_and_black_to_b():
    board = Board()
    assert board_to_fen(board).split()[1] == "w"

    board.current_player = Color.BLACK
    assert board_to_fen(board).split()[1] == "b"


# ---------------------------------------------------------------------------
# board_from_fen
# ---------------------------------------------------------------------------

def test_round_trip_starting_position():
    board = Board()
    fen = board_to_fen(board)

    restored = board_from_fen(fen)

    assert board_to_fen(restored) == fen


def test_parses_a_real_world_external_fen_correctly():
    # A genuine mid-game FEN pulled from an external source (not
    # generated by this project), used as an independent correctness
    # check rather than only round-tripping our own encoder/decoder
    # against itself.
    fen = "1nbakabn1/r7r/1c7/p1p1C1p1p/4C2c1/9/P1P1P1P1P/9/9/RNBAKABNR b - - 4 4"

    board = board_from_fen(fen)

    assert board.current_player == Color.BLACK
    black_horse = board.board[9][1]
    assert black_horse.type == PieceType.HORSE and black_horse.color == Color.BLACK
    black_elephant = board.board[9][2]
    assert black_elephant.type == PieceType.ELEPHANT and black_elephant.color == Color.BLACK
    red_cannon_1 = board.board[6][4]
    assert red_cannon_1.type == PieceType.CANNON and red_cannon_1.color == Color.RED
    red_cannon_2 = board.board[5][4]
    assert red_cannon_2.type == PieceType.CANNON and red_cannon_2.color == Color.RED
    black_cannon = board.board[5][7]
    assert black_cannon.type == PieceType.CANNON and black_cannon.color == Color.BLACK
    red_back_rank = "".join(
        p.type.value if p else "." for p in board.board[0]
    )
    assert red_back_rank == "RHEAKAEHR"  # our own PieceType.value letters, for readability
    assert board.board[0][0].color == Color.RED


def test_round_trip_a_sparse_custom_position():
    board = empty_board()
    put(board, PieceType.KING, Color.RED, 4, 0)
    put(board, PieceType.KING, Color.BLACK, 4, 9)
    put(board, PieceType.ROOK, Color.RED, 0, 5)
    put(board, PieceType.PAWN, Color.BLACK, 3, 6)
    board.current_player = Color.BLACK

    fen = board_to_fen(board)
    restored = board_from_fen(fen)

    assert board_to_fen(restored) == fen
    assert restored.current_player == Color.BLACK
    assert restored.board[5][0].type == PieceType.ROOK
    assert restored.board[5][0].color == Color.RED
    assert restored.board[6][3].type == PieceType.PAWN
    assert restored.board[6][3].color == Color.BLACK


def test_rejects_malformed_fen():
    with pytest.raises(ValueError):
        board_from_fen("not a real fen")

    with pytest.raises(ValueError):
        board_from_fen("rnbakabnr/9 w - - 0 1")  # too few ranks
