"""
AlphaZetaChess external game importer (V0.6.2 data expansion).

Converts real human/engine games from `trainingdata/` (ICCS-notation
`.pgns` files, ~140k games combined across the WXF and dpxq sources --
see `trainingdata/readme.txt`) into this project's own V0.5.1
self-play record format, so the EXISTING `tools/
label_positions_with_pikafish.py` can sample and label positions from
them exactly like it does for `data/selfplay.jsonl` -- real human/
engine games are far more diverse and realistic than a self-play
corpus generated by this project's own comparatively weak engine, and
there's no additional self-play compute cost to using them.

## Coordinate convention -- verified against authoritative sources, not assumed

ICCS file letters A-I map DIRECTLY to this project's x=0-8 (confirmed
against the rec.games.chinese-chess FAQ: "the rows are A to I from
left to right (from red's viewpoint)" -- i.e. no mirroring), and rank
digits 0-9 map directly to y=0-9 (Red's back rank to Black's). This
was cross-checked two ways before trusting it: (1) the authoritative
spec, and (2) the fact that these particular `.pgns` files' own
`[FEN ...]` header for the standard starting position is byte-for-byte
identical to this project's own `core/fen.py`'s `board_to_fen(Board())`
output -- strong independent evidence both use the same absolute grid.
(A pure legal-move replay check, tried first, could NOT distinguish
the correct orientation from its horizontal mirror image, since
Xiangqi's rules are themselves left-right symmetric -- every game
replays as "legal" under either orientation. Recorded here so nobody
re-derives that dead end.)

## Every decoded game is re-validated against this project's own Rule engine

Not just parsed and trusted: each move is checked with
`Rule.is_legal_move` as it's replayed, and the entire game is
discarded (not partially included) if any move fails -- a strong
quality gate against parsing bugs or PGN dialect quirks this script
doesn't handle (e.g. genuinely illegal recorded moves, malformed
entries), and a strong correctness signal for the importer itself: if
the coordinate mapping above were wrong, the overwhelming majority of
real games would fail validation almost immediately, not silently
produce nonsense.

Usage:
    python tools/import_external_games.py --input trainingdata_extracted/wxf-41743games.pgns \\
        --output data/external_games.jsonl --max-games 3000
"""

import argparse
import os
import re
import sys

sys.path.insert(
    0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src")
)

from alphazetacchess.core.board import Board
from alphazetacchess.core.rule import Rule
from alphazetacchess.core.move import Move
from alphazetacchess.core.piece import Color
from alphazetacchess.selfplay.recorder import append_record

_MOVE_RE = re.compile(r"([A-I])(\d)-([A-I])(\d)")
_RESULT_MAP = {"1-0": "RED_WINS", "0-1": "BLACK_WINS", "1/2-1/2": "DRAW"}


def file_to_x(letter):
    return ord(letter) - ord("A")


def parse_games(pgns_text):
    """Yield (moves, result) for every game in a raw `.pgns` file's text.
    `moves` is a list of ((from_x, from_y), (to_x, to_y)) tuples."""
    for chunk in pgns_text.split('[Game "Chinese Chess"]')[1:]:
        result_match = re.search(r'\[Result\s+"([^"]*)"\]', chunk)
        result = _RESULT_MAP.get(result_match.group(1).strip()) if result_match else None
        if result is None:
            continue  # unknown/unfinished game -- not usable as a labeled outcome

        body = re.sub(r"\[.*?\]", "", chunk, flags=re.DOTALL)
        body = re.sub(r"\d+\.", "", body)
        body = re.sub(r"\s*(1-0|0-1|1/2-1/2|\*)\s*$", "", body.strip())

        moves = [
            ((file_to_x(fx), int(fy)), (file_to_x(tx), int(ty)))
            for fx, fy, tx, ty in _MOVE_RE.findall(body)
        ]
        if moves:
            yield moves, result


def validate_and_convert(moves, result, source_name):
    """
    Replay `moves` against a fresh Board, checking every move's
    legality with Rule.is_legal_move. Returns a V0.5.1-format record
    dict, or None if any move turns out illegal (the whole game is
    discarded, not partially included -- see module docstring).
    """
    board = Board()
    color = Color.RED
    record_moves = []

    for from_pos, to_pos in moves:
        move = Move(from_pos, to_pos)
        if not Rule.is_legal_move(board, move, color):
            return None

        record_moves.append({"color": color.name, "from": list(from_pos), "to": list(to_pos)})
        board.move(from_pos, to_pos)
        color = Board.opponent(color)

    return {
        "red_config": {"source": source_name},
        "black_config": {"source": source_name},
        "result": result,
        "total_moves": len(record_moves),
        "moves": record_moves,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input", required=True, help="path to an unzipped .pgns file")
    parser.add_argument("--output", default="data/external_games.jsonl")
    parser.add_argument("--max-games", type=int, default=3000, help="randomly sample at most this many valid games")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--source-name", default=None, help="defaults to the input filename")
    args = parser.parse_args()

    source_name = args.source_name or os.path.basename(args.input)

    print(f"Reading {args.input}...")
    with open(args.input, encoding="utf-8", errors="replace") as f:
        text = f.read()

    parsed = list(parse_games(text))
    print(f"Parsed {len(parsed)} game(s) with a known result out of the file.")

    import random
    rng = random.Random(args.seed)
    rng.shuffle(parsed)

    written = 0
    skipped_illegal = 0

    for moves, result in parsed:
        if written >= args.max_games:
            break

        record = validate_and_convert(moves, result, source_name)
        if record is None:
            skipped_illegal += 1
            continue

        append_record(args.output, record)
        written += 1

        if written % 200 == 0:
            print(f"  ...{written} valid games written so far")

    print(f"\nDone. {written} valid game(s) written to {args.output}")
    print(f"Skipped {skipped_illegal} game(s) that failed legal-move replay validation.")
    if written > 0 and skipped_illegal / (written + skipped_illegal) > 0.1:
        print(
            "WARNING: more than 10% of games failed validation -- this might indicate "
            "a parsing issue rather than just noisy source data. Worth investigating "
            "before trusting the output."
        )


if __name__ == "__main__":
    main()
